# IMAGEN MODELO
FROM eclipse-temurin:21.0.6_7-jdk

# INFORMAR EL PUERTO DONDE SE EJECUTA EL CONTENEDOR(INFORMATIVO)
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ
WORKDIR /root

# COPIAR Y PEGAR ARCHIVOS DENTRO DEL CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# DAR PERMISO
RUN chmod +x mvnw

# DESCARGAR LAS DEPENDENCIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CODIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src

# CONSTRUIR NUESTRA APLICACION
RUN ./mvnw clean install -DskipTests

# LEVANTAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java", "-jar", "/root/target/taskifyApi-0.0.1-SNAPSHOT.jar"]

