spring:
  application:
    name: taskifyApi

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}

# FILE SIZE
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

# AUTHENTICATION
  security:
    oauth2:
      client:
        registration:
          # GOOGLE
          google:
            client-id: ${GOOGLE_AUTH_ID_CLIENT}
            client-secret: ${GOOGLE_AUTH_SECRET_CLIENT}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_AUTH_ID_CLIENT}
            client-secret: ${GITHUB_AUTH_SECRET_CLIENT}
            scope:
              - read:user
              - user:email

# SECURITY
app:
  # COOKIE
  cookie:
    secure: ${COOKIE_SECURE:false}

  # SECURITY & JWT
  security:
    jwt-expiration-ms: ${JWT_EXPIRATION:86400000}
    jwt-key-secret: ${JWT_KEY_SECRET}
    jwt-issuer-name: ${ISSUER_GENERATOR}

# URL FRONTEND
web:
  url: ${APP_WEB_URL}

# STORAGE
storage:
  type: ${STORAGE_TYPE:minio}

# FIREBASE
firebase:
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}

# MINIO STORAGE
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  url-expiration-seconds: ${MINIO_URL_EXPIRATION:3600}

# EMAIL
email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}